<?php

namespace Training\Test\Controller\Action;


class Index extends \Magento\Framework\App\Action\Action
{
    /**
     * Test action index
     */
    public function execute() {
//        $this->getResponse()->appendBody("HELLO WORLD");
//        $this->_redirect('catalog/category/view/id/3');
        $block = $this->_view->getLayout()->createBlock('Training\Test\Block\Template');
        $block->setTemplate('Training_Test::test.phtml');
        $this->getResponse()->appendBody($block->toHtml());


    }


//    /**
//     * Check if admin has permissions to visit related pages
//     *
//     * @return bool
//     */
//    protected function _isAllowed() {
//        $secret = $this->getRequest()->getParam('secret');
//        return isset($secret) && (int)$secret==1;
//    }
/*
INSERT INTO url_rewrite SET request_path=’testpage.html’, target_path=’test/action/index’, redirect_type=0, store_id=1, is_autogenerated=0;
*/

}